### ISSUE TITLE
Make a Wrapper for ROS2 Gazebo Interface

### ISSUE THREAD

**Issue by maya-dc-patel** [maya-dc-patel/RLCJ#1]

**Comment by iSkytran** [comment]
After investigation, using the Gazebo simulator seems to not be the best fit for our project. Since reinforcement learning requires many iterations of training, Gazebo run slower compared to MuJoCo. MuJoCo also works out of the box with Farama Gymnasium, so no ROS2 driver is needed. However, a wrapper/custom environment is still needed.

**Comment by iSkytran** [comment]
Moving toward the Clearpath Jackal has allowed us to continue using Gazebo as our simulator, albeit it will be with Gazebo Classic.
